[package]
name = "bitwisdom"
version = "0.2.1"
edition = "2024"
description = "Bit manipulation in Rust, no-std, no-unsafe, const support"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Marco-Farruggio/bitwisdom"
keywords = ["bit", "bitwise", "bits", "no-std"]
categories = ["no-std"]

[dependencies]